### ISSUE TITLE
Create and document script to Deploy K8s and CNFs to Packet.net

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testbed#107]
### Deploy K8s

- [x] Create environment configuration template for Kubecon test case.  See #99 
- [x] Add steps to use k8s deploy from comparison/kubecon18-chained_nf_test/run_k8s_benchmark.sh deploys a working k8s cluster
- [x] Ensure kubeconfig is created in comparison/kubecon18-chained_nf_test
- [ ] Update dev and user docs
   - https://github.com/cncf/cnfs/tree/master/comparison/kubecon18-chained_nf_test/docs
   - https://github.com/cncf/cnfs/blob/master/comparison/kubecon18-chained_nf_test/README.md
 
### Deploy CNFs to K8s

Ansible:
- [x] Create top level playbook for the test case calling other playbooks
Deferred:
- [x] additional retry support on failures (eg. network, API)

Scripts / Helm for deploying CNFs:

- [ ] Create script (`deploy_cnf_testcase.sh`) to deploy the chained CNF pipeline test case
   * Takes the argument `pipeline` and deploys the CNFs to K8s for the pipeline test case
   - [ ] Support single chain with static depth of 7
   - [ ] Support multi-chain with static depth of 2 with 3 chains
   - [ ] Add support for variable depth and number of chains (allowing over subscription) 

- [ ] Create script to deploy the chained CNF snake test case
   - [ ] Support single chain with static depth of 7
   - [ ] Support multi-chain with static depth of 2 with 3 chains
   - [ ] Add support for variable depth and number of chains (allowing over subscription) 

- [ ] Update helm code to handle the bash version of the pipeline test case
- [ ] Update helm code to handle the bash version of the snake test case

- [ ] Update dev and user docs
   - https://github.com/cncf/cnfs/tree/master/comparison/kubecon18-chained_nf_test/docs
   - https://github.com/cncf/cnfs/blob/master/comparison/kubecon18-chained_nf_test/README.md

**Comment by denverwilliams** [comment]
https://github.com/cncf/cnfs/commit/0408c2083ad0037c181e22c5bdbbb9102643b83d
https://github.com/cncf/cnfs/commit/06ed3bde2af4dd5ed55943aa084d57acc3031a23

**Comment by denverwilliams** [comment]
https://github.com/cncf/cnfs/commit/a48c2eef8c7bbe516f7c0fd579402066c79fd30e, was an attempt to fetch the worker node ip and register the node with a dns record on the fly before the node creation has a chance to timeout due to https://github.com/cncf/cnfs/issues/152
Unfortunately the way Terraform is handling resources this data is not available on the fly before complete allocation is done, so this will not work.

Going forward we can potentially use the packet.net cli client to fetch the nodes public ip(providing it's available in the cli) by using the nodes hostname as a uuid(which we can fetch dynamically using a method like https://github.com/cncf/cnfs/blob/master/comparison/kubecon18-chained_nf_test/run_k8s_benchmark.sh#L4)

**Comment by denverwilliams** [comment]
We are now successfully able to deploy reserved instances using https://github.com/cncf/cnfs/commit/b02d7eaeeec0fcfa7579a45a1f67055fc49ff2a5 which lets use fetch the necessary ips from k8s.

**Comment by taylor** [comment]
Completed:
- [x] Deploy script for k8s cluser
- [x] Script to deploy CNFs using helm

Remaining:
- Templates supporting Snake test case
  * Possibly use a different implementation for configuring VPP so we do not end up with a ton of templates
- Documentation for using the scripts above from nothing to fully deployed

**Comment by taylor** [comment]
Will open new ticket for remaining items.
